let Constructions = {
    "Construction_Beehive": {
        "BuildComplete": " VFX_BuildComplete_Lumber ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Making",
        "Id": 4014,
        "Name": "Construction_Beehive",
        "ProximityBonus": "None",
        "Req1": "Lumber",
        "Req2": "Wood",
        "Req3": "none",
        "Time0": 20,
        "Value1": 3,
        "Value2": 1,
        "Value3": 0
    },
    "Construction_Cold_Storage": {
        "BuildComplete": " VFX_BuildComplete_Lumber ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Building",
        "Id": 4019,
        "Name": "Construction_Cold_Storage",
        "ProximityBonus": "Energy",
        "Req1": "Ice_Block",
        "Req2": "Lumber",
        "Req3": "Energy",
        "Time0": 30,
        "Value1": 5,
        "Value2": 10,
        "Value3": 10
    },
    "Construction_Double_Iron": {
        "BuildComplete": " VFX_BuildComplete_Iron ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Constructing",
        "Id": 4008,
        "Name": "Construction_Double_Iron",
        "ProximityBonus": "Iron,Energy",
        "Req1": "Iron",
        "Req2": "Lumber",
        "Req3": "Energy",
        "Time0": 90,
        "Value1": 2,
        "Value2": 2,
        "Value3": 10
    },
    "Construction_Double_Lumber": {
        "BuildComplete": " VFX_BuildComplete_Lumber ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Building",
        "Id": 4007,
        "Name": "Construction_Double_Lumber",
        "ProximityBonus": "Energy",
        "Req1": "Lumber",
        "Req2": "Wood",
        "Req3": "Energy",
        "Time0": 90,
        "Value1": 10,
        "Value2": 10,
        "Value3": 10
    },
    "Construction_Double_Steel": {
        "BuildComplete": " VFX_BuildComplete_Steel ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Erecting",
        "Id": 4009,
        "Name": "Construction_Double_Steel",
        "ProximityBonus": "Iron,Energy",
        "Req1": "Steel",
        "Req2": "Iron",
        "Req3": "Energy",
        "Time0": 180,
        "Value1": 10,
        "Value2": 10,
        "Value3": 10
    },
    "Construction_Fish_Farms": {
        "BuildComplete": " VFX_BuildComplete_Water ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Filling",
        "Id": 4018,
        "Name": "Construction_Fish_Farms",
        "ProximityBonus": "Seaweed,Water",
        "Req1": "Seaweed",
        "Req2": "Water",
        "Req3": "none",
        "Time0": 10,
        "Value1": 10,
        "Value2": 20,
        "Value3": 0
    },
    "Construction_Fishing_Employees": {
        "BuildComplete": " VFX_BuildComplete_Wood ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Assembling",
        "Id": 4022,
        "Name": "Construction_Fishing_Employees",
        "ProximityBonus": "Energy",
        "Req1": "Oak_Wood",
        "Req2": "Wood",
        "Req3": "Energy",
        "Time0": 90,
        "Value1": 5,
        "Value2": 5,
        "Value3": 5
    },
    "Construction_Fishing_Platforms": {
        "BuildComplete": " VFX_BuildComplete_Water ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Constructing",
        "Id": 4021,
        "Name": "Construction_Fishing_Platforms",
        "ProximityBonus": "Water",
        "Req1": "Water",
        "Req2": "Lumber",
        "Req3": "Oak_Wood",
        "Time0": 30,
        "Value1": 25,
        "Value2": 5,
        "Value3": 5
    },
    "Construction_Free": {
        "BuildComplete": "VFX_BuildComplete_Free",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Getting",
        "Id": 4000,
        "Name": "Construction_Free",
        "ProximityBonus": "None",
        "Req1": "none",
        "Req2": "none",
        "Req3": "none",
        "Time0": 4,
        "Value1": 0,
        "Value2": 0,
        "Value3": 0
    },
    "Construction_High_Labor": {
        "BuildComplete": " VFX_BuildComplete_Lumber ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Building",
        "Id": 4017,
        "Name": "Construction_High_Labor",
        "ProximityBonus": "None",
        "Req1": "Stars",
        "Req2": "Lumber",
        "Req3": "Wood",
        "Time0": 60,
        "Value1": 150000,
        "Value2": 5,
        "Value3": 5
    },
    "Construction_Iron": {
        "BuildComplete": "VFX_BuildComplete_Iron",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Constructing",
        "Id": 4003,
        "Name": "Construction_Iron",
        "ProximityBonus": "Iron,Energy",
        "Req1": "Iron",
        "Req2": "Lumber",
        "Req3": "Energy",
        "Time0": 90,
        "Value1": 1,
        "Value2": 1,
        "Value3": 5
    },
    "Construction_Lumber": {
        "BuildComplete": "VFX_BuildComplete_Lumber",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Building",
        "Id": 4002,
        "Name": "Construction_Lumber",
        "ProximityBonus": "Energy",
        "Req1": "Lumber",
        "Req2": "Wood",
        "Req3": "Energy",
        "Time0": 60,
        "Value1": 5,
        "Value2": 5,
        "Value3": 5
    },
    "Construction_Lumber_Lite": {
        "BuildComplete": "VFX_BuildComplete_Steel",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Building",
        "Id": 4006,
        "Name": "Construction_Lumber_Lite",
        "ProximityBonus": "None",
        "Req1": "Lumber",
        "Req2": "none",
        "Req3": "none",
        "Time0": 8,
        "Value1": 1,
        "Value2": 0,
        "Value3": 0
    },
    "Construction_Nuclear": {
        "BuildComplete": " VFX_BuildComplete_Steel ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Building",
        "Id": 4016,
        "Name": "Construction_Nuclear",
        "ProximityBonus": "Iron",
        "Req1": "Stars",
        "Req2": "Steel",
        "Req3": "Iron",
        "Time0": 120,
        "Value1": 10000000,
        "Value2": 5,
        "Value3": 5
    },
    "Construction_Oak_Fish_Lite": {
        "BuildComplete": " VFX_BuildComplete_Wood ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Constructing",
        "Id": 4023,
        "Name": "Construction_Oak_Fish_Lite",
        "ProximityBonus": "Water",
        "Req1": "Oak_Wood",
        "Req2": "Water",
        "Req3": "none",
        "Time0": 10,
        "Value1": 5,
        "Value2": 5,
        "Value3": 0
    },
    "Construction_Oak_Lite": {
        "BuildComplete": " VFX_BuildComplete_Wood ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Making",
        "Id": 4012,
        "Name": "Construction_Oak_Lite",
        "ProximityBonus": "None",
        "Req1": "Wood",
        "Req2": "Oak_Wood",
        "Req3": "none",
        "Time0": 8,
        "Value1": 2,
        "Value2": 1,
        "Value3": 0
    },
    "Construction_Oak_Wood": {
        "BuildComplete": " VFX_BuildComplete_Wood ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Building",
        "Id": 4010,
        "Name": "Construction_Oak_Wood",
        "ProximityBonus": "None",
        "Req1": "Wood",
        "Req2": "Oak_Wood",
        "Req3": "none",
        "Time0": 30,
        "Value1": 3,
        "Value2": 3,
        "Value3": 0
    },
    "Construction_Paved_Road": {
        "BuildComplete": " VFX_BuildComplete_Lumber ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Building",
        "Id": 4011,
        "Name": "Construction_Paved_Road",
        "ProximityBonus": "None",
        "Req1": "Lumber",
        "Req2": "Wood",
        "Req3": "none",
        "Time0": 15,
        "Value1": 1,
        "Value2": 3,
        "Value3": 0
    },
    "Construction_Quadruple_Lumber": {
        "BuildComplete": " VFX_BuildComplete_Lumber ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Building",
        "Id": 4020,
        "Name": "Construction_Quadruple_Lumber",
        "ProximityBonus": "None",
        "Req1": "Oak_Wood",
        "Req2": "Wood",
        "Req3": "Lumber",
        "Time0": 30,
        "Value1": 20,
        "Value2": 10,
        "Value3": 5
    },
    "Construction_Salty_Water": {
        "BuildComplete": " VFX_BuildComplete_Water ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Filling",
        "Id": 4017,
        "Name": "Construction_Salty_Water",
        "ProximityBonus": "Water",
        "Req1": "Brine",
        "Req2": "Water",
        "Req3": "none",
        "Time0": 4,
        "Value1": 2,
        "Value2": 3,
        "Value3": 0
    },
    "Construction_Special_Buildings": {
        "BuildComplete": " VFX_BuildComplete_Lumber ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Constructing",
        "Id": 4015,
        "Name": "Construction_Special_Buildings",
        "ProximityBonus": "None",
        "Req1": "Stars",
        "Req2": "Oak_Wood",
        "Req3": "Lumber",
        "Time0": 60,
        "Value1": 5000000,
        "Value2": 20,
        "Value3": 20
    },
    "Construction_Steel": {
        "BuildComplete": "VFX_BuildComplete_Steel",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Erecting",
        "Id": 4004,
        "Name": "Construction_Steel",
        "ProximityBonus": "Iron,Energy",
        "Req1": "Steel",
        "Req2": "Iron",
        "Req3": "Energy",
        "Time0": 120,
        "Value1": 5,
        "Value2": 5,
        "Value3": 5
    },
    "Construction_Water": {
        "BuildComplete": "VFX_BuildComplete_Water",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Filling",
        "Id": 4005,
        "Name": "Construction_Water",
        "ProximityBonus": "Water",
        "Req1": "Water",
        "Req2": "none",
        "Req3": "none",
        "Time0": 4,
        "Value1": 10,
        "Value2": 0,
        "Value3": 0
    },
    "Construction_Water_Lite": {
        "BuildComplete": " VFX_BuildComplete_Water ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Filling",
        "Id": 4025,
        "Name": "Construction_Water_Lite",
        "ProximityBonus": "Water",
        "Req1": "Water",
        "Req2": "none",
        "Req3": "none",
        "Time0": 4,
        "Value1": 4,
        "Value2": 0,
        "Value3": 0
    },
    "Construction_Wood_1": {
        "BuildComplete": "VFX_BuildComplete_Wood",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Making",
        "Id": 4001,
        "Name": "Construction_Wood_1",
        "ProximityBonus": "None",
        "Req1": "Wood",
        "Req2": "none",
        "Req3": "none",
        "Time0": 8,
        "Value1": 1,
        "Value2": 0,
        "Value3": 0
    },
    "Construction_Wood_10": {
        "BuildComplete": "VFX_BuildComplete_Wood",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Building",
        "Id": 4008,
        "Name": "Construction_Wood_10",
        "ProximityBonus": "None",
        "Req1": "Wood",
        "Req2": "none",
        "Req3": "none",
        "Time0": 20,
        "Value1": 10,
        "Value2": 0,
        "Value3": 0
    },
    "Construction_Wood_20": {
        "BuildComplete": " VFX_BuildComplete_Wood ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Building",
        "Id": 4013,
        "Name": "Construction_Wood_20",
        "ProximityBonus": "None",
        "Req1": "Wood",
        "Req2": "none",
        "Req3": "none",
        "Time0": 24,
        "Value1": 20,
        "Value2": 0,
        "Value3": 0
    },
    "Construction_Wood_3": {
        "BuildComplete": "VFX_BuildComplete_Wood",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Making",
        "Id": 4006,
        "Name": "Construction_Wood_3",
        "ProximityBonus": "None",
        "Req1": "Wood",
        "Req2": "none",
        "Req3": "none",
        "Time0": 12,
        "Value1": 3,
        "Value2": 0,
        "Value3": 0
    },
    "Construction_Wood_5": {
        "BuildComplete": "VFX_BuildComplete_Wood",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Building",
        "Id": 4007,
        "Name": "Construction_Wood_5",
        "ProximityBonus": "None",
        "Req1": "Wood",
        "Req2": "none",
        "Req3": "none",
        "Time0": 16,
        "Value1": 5,
        "Value2": 0,
        "Value3": 0
    },
    "Construction_Wood_Water": {
        "BuildComplete": " VFX_BuildComplete_Wood ",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Assembling",
        "Id": 4024,
        "Name": "Construction_Wood_Water",
        "ProximityBonus": "Water",
        "Req1": "Wood",
        "Req2": "Water",
        "Req3": "none",
        "Time0": 10,
        "Value1": 5,
        "Value2": 1,
        "Value3": 0
    },
	"Construction_Water4": {
        "BuildComplete": "VFX_BuildComplete_Wood",
        "BuildVFX": "VFX_BuildLoop",
        "CraftingText": "Making",
        "Id": 4006,
        "Name": "Construction_Water4",
        "ProximityBonus": "None",
        "Req1": "Water",
        "Req2": "none",
        "Req3": "none",
        "Time0": 12,
        "Value1": 4,
        "Value2": 0,
        "Value3": 0
    }
}